In [7]:
import pandas as pd
import sys
import numpy as np
import os

limit row output as needed

In [8]:
from notebook.services.config import ConfigManager
cm = ConfigManager().update('notebook', {'limit_output': 200})

option to install packages if missing

In [9]:
def install(name):
    import subprocess
    subprocess.call(['pip', 'install', name])

Path to data files

In [10]:
path='/Users/daelsaid/Downloads/subjectlist'

generate dataframes of the relevant behavioral files to merge  

*datafile_to_merge_df = data_eff_wide_revised csv file*   
*datafile_final = csv file with subject order that matches analysis files*

set 2 dataframes and include subject, group, session, efficiency scores and subject list order

In [13]:
datafile_to_merge=os.path.join(path,'orig/data_eff_wide_revised.csv')
datafile_final=os.path.join(path,'orig/all_subj_ordered.csv')

datafile_to_merge_df=pd.read_csv(datafile_to_merge,dtype='str')
datafile_final_df=pd.read_csv(datafile_final,dtype='str')
datafile_to_merge_df
datafile_final_df

   index_subjlistorder   pid visit session subgroup_type
0                    1  7047     1       1            td
1                    2  7054     1       1            td
2                    3  7083     1       1            td
3                    4  7095     1       1            td
4                    5  7103     1       1            td
5                    6  7117     1       1            td
6                    7  7148     1       1            td
7                    8  7166     1       1            td
8                    9  7194     1       1            td
9                   10  7201     1       1            td
10                  11  7228     1       1            td
11                  12  7233     1       1            td
12                  13  7235     1       1            td
13                  14  7275     1       1            td
14                  15  7279     1       1            td
15                  16  7287     1       1            td
16                  17  7306     1       1            td
17                  18  7320     1       1            td
18                  19  7324     1       1            td
19                  20  7334     1       1            td
20                  21  7603     1       1            td
21                  22  7047     2       1            td
22                  23  7054     2       1            td
23                  24  7083     2       1            td
24                  25  7095     2       1            td
25                  26  7103     2       1            td
26                  27  7117     2       1            td
27                  28  7148     2       1            td
28                  29  7166     2       1            td
29                  30  7194     2       1            td
..                 ...   ...   ...     ...           ...
50                  51  7294     1       1            md
51                  52  7322     1       1            md
52                  53  7325     1       1            md
53                  54  7348     1       1            md
54                  55  7363     1       1            md
55                  56  7366     1       1            md
56                  57  7367     1       1            md
57                  58  7397     1       1            md
58                  59  7399     1       1            md
59                  60  7546     1       1            md
60                  61  7784     1       1            md
61                  62  7045     2       1            md
62                  63  7091     2       1            md
63                  64  7098     2       1            md
64                  65  7170     2       1            md
65                  66  7187     2       1            md
66                  67  7188     2       1            md
67                  68  7223     2       1            md
68                  69  7281     2       1            md
69                  70  7294     2       1            md
70                  71  7322     2       1            md
71                  72  7325     2       1            md
72                  73  7348     2       1            md
73                  74  7363     2       1            md
74                  75  7366     2       1            md
75                  76  7367     2       1            md
76                  77  7397     2       1            md
77                  78  7399     2       1            md
78                  79  7546     2       1            md
79                  80  7784     2       1            md

[80 rows x 5 columns]

create empty df to append info to

In [14]:
merged_df=pd.DataFrame()

Merge dataframes using pid as the unique identifier

In [16]:
merged_df=datafile_final_df.merge(datafile_to_merge_df,on='pid',how='left',copy=False)
merged_df

,index_subjlistorder,pid,visit,session,subgroup_type,group,subgroup,fluency.pre,fluency.gain,eff.comp.num.gain,...,acc.add.post,corr.rt.add.post,eff.add1.post,acc.add1.post,rt.add1.post,corr.rt.add1.post,eff.add2.post,acc.add2.post,rt.add2.post,corr.rt.add2.post
0,1,7047,1,1,td,Training,TD_Tutoring,102,19,0.08,...,0.96,1325.62,0.76,0.92,1356.33,1212.77,0.7,1,1438.46,1438.46
1,2,7054,1,1,td,Training,TD_Tutoring,121,-11,-0.64,...,0.48,1273.78,0.55,0.71,1267.2,1287.88,0.2,0.25,1259.67,1259.67
2,3,7083,1,1,td,Training,TD_Tutoring,102,-12,0.39,...,0.88,1955.15,0.59,0.96,1601.79,1636.3,0.35,0.79,2247.75,2274
3,4,7095,1,1,td,Training,TD_Tutoring,101,2,-0.24,...,0.71,1100.34,0.84,0.92,1338.88,1101,0.45,0.5,1618.5,1099.67
4,5,7103,1,1,td,Training,TD_Tutoring,112,-2,0.44,...,0.88,2763.89,0.28,0.88,3343.91,3117.67,0.37,0.88,2505.48,2410.1
5,6,7117,1,1,td,Training,TD_Tutoring,116,9,0.29,...,0.96,1434.71,0.67,0.92,1345.42,1363.95,0.66,1,1505.46,1505.46
6,7,7148,1,1,td,Training,TD_Tutoring,102,-8,0.37,...,0.9,985.48,0.88,0.88,996.04,1002.1,0.95,0.92,970.08,968.86
7,8,7166,1,1,td,Training,TD_Tutoring,101,-3,0.15,...,0.5,1021,0.58,0.58,1025.25,1007.5,0.41,0.42,962.26,1034.5
8,9,7194,1,1,td,Training,TD_Tutoring,96,3,0.26,...,0.96,1284.79,0.66,0.96,1513.21,1445.87,0.85,0.96,1105.71,1123.7
9,10,7201,1,1,td,Training,TD_Tutoring,92,4,0.23,...,0.94,1156.37,0.9,1,1106.83,1106.83,0.73,0.88,1209.29,1205.9
10,11,7228,1,1,td,Training,TD_Tutoring,96,10,0.23,...,0.86,3347.5,0.3,0.79,2590.05,2669.63,0.23,0.92,4146.78,4025.36
11,12,7233,1,1,td,Training,TD_Tutoring,111,16,-0.11,...,0.94,2028.62,0.48,0.96,1969.38,2003.09,0.45,0.92,2234.13,2054.14
12,13,7235,1,1,td,Training,TD_Tutoring,115,12,0.18,...,0.75,1825.03,0.45,0.83,2268.29,1827.5,0.37,0.67,1872.74,1822.56
13,14,7275,1,1,td,Training,TD_Tutoring,110,3,-0.09,...,0.98,1294.81,0.71,0.96,1335.58,1361.61,0.81,1,1228,1228
14,15,7279,1,1,td,Training,TD_Tutoring,107,-3,0.18,...,0.94,964.28,0.93,0.92,983.5,984.55,1.02,0.96,964.38,944
15,16,7287,1,1,td,Training,TD_Tutoring,97,-8,0.19,...,0.88,1920.41,0.38,0.88,2238.95,2309.05,0.57,0.88,1502.3,1531.76
16,17,7306,1,1,td,Training,TD_Tutoring,92,-12,0.31,...,0.63,2256.14,0.27,0.63,2542.64,2375.8,0.29,0.63,2407.32,2136.47
17,18,7320,1,1,td,Training,TD_Tutoring,93,-16,0.19,...,0.79,2209.91,0.38,0.75,2251.58,1960.72,0.34,0.83,2570.52,2459.1
18,19,7324,1,1,td,Training,TD_Tutoring,96,-8,-0.06,...,0.8,1205.11,0.87,0.96,1104.38,1104.35,0.48,0.63,1312.04,1305.87
19,20,7334,1,1,td,Training,TD_Tutoring,92,-4,0.36,...,0.79,1270.96,0.63,0.83,1280.75,1312.8,0.61,0.75,1263,1229.11
20,21,7603,1,1,td,Training,TD_Tutoring,97,-6,-0.04,...,0.88,944.12,0.87,0.92,1080.33,1059.68,1,0.83,1015.92,828.55
21,22,7047,2,1,td,Training,TD_Tutoring,102,19,0.08,...,0.96,1325.62,0.76,0.92,1356.33,1212.77,0.7,1,1438.46,1438.46
22,23,7054,2,1,td,Training,TD_Tutoring,121,-11,-0.64,...,0.48,1273.78,0.55,0.71,1267.2,1287.88,0.2,0.25,1259.67,1259.67
23,24,7083,2,1,td,Training,TD_Tutoring,102,-12,0.39,...,0.88,1955.15,0.59,0.96,1601.79,1636.3,0.35,0.79,2247.75,2274
24,25,7095,2,1,td,Training,TD_Tutoring,101,2,-0.24,...,0.71,1100.34,0.84,0.92,1338.88,1101,0.45,0.5,1618.5,1099.67
25,26,7103,2,1,td,Training,TD_Tutoring,112,-2,0.44,...,0.88,2763.89,0.28,0.88,3343.91,3117.67,0.37,0.88,2505.48,2410.1
26,27,7117,2,1,td,Training,TD_Tutoring,116,9,0.29,...,0.96,1434.71,0.67,0.92,1345.42,1363.95,0.66,1,1505.46,1505.46
27,28,7148,2,1,td,Training,TD_Tutoring,102,-8,0.37,...,0.9,985.48,0.88,0.88,996.04,1002.1,0.95,0.92,970.08,968.86
28,29,7166,2,1,td,Training,TD_Tutoring,101,-3,0.15,...,0.5,1021,0.58,0.58,1025.25,1007.5,0.41,0.42,962.26,1034.5
29,30,7194,2,1,td,Training,TD_Tutoring,96,3,0.26,...,0.96,1284.79,0.66,0.96,1513.21,1445.87,0.85,0.96,1105.71,1123.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,51,7294,1,1,md,Training,MLD_Tutoring,86,-3,0.31,...,0.9,3184.97,0.26,0.88,3535.74,3344.76,0.3,0.92,3066,3025.18
51,52,7322,1,1,md,Training,MLD_Tutoring,90,0,-0.01,...,0.9,1191.94,0.88,0.96,1088.96,1091.52,0.64,0.83,1366.67,1292.35
52,53,7325,1,1,md,Training,MLD_Tutoring,90,2,0.14,...,0.88,1961,0.41,0.88,2234.82,2162.67,0.5,0.88,1963.83,1759.33
53,54,7348,1,1,md,Training,MLD_Tutoring,83,6,0.01,...,0.79,1497.34,0.7,0.83,1163.67,1192.85,0.42,0.75,1793.17,1801.83
54,55,7363,1,1,md,Training,MLD_Tutoring,88,0,-0.02,...,0.69,2621.12,0.32,0.75,2667.86,2374.44,0.22,0.63,3282.81,2867.8
55,56,7366,1,1,md,Training,MLD_Tutoring,89,-4,0.08,...,0.88,1139.32,0.6,0.79,1424.5,1326.11,1.01,0.96,937.79,952.52
56,57,7367,1,1,md,Training,MLD_Tutoring,80,6,0.23,...,0.81,1809.95,0.47,0.79,1809.38,1688.84,0.43,0.83,1972,1931.05
57,58,7397,1,1,md,Training,MLD_Tutoring,86,11,0.29,...,0.94,1025.15,0.84,0.92,1343.21,1090.77,1,0.96,967.13,959.52
58,59,7399,1,1,md,Training,MLD_Tutoring,82,20,0.48,...,0.96,1778.64,0.5,0.96,2050.13,1931.57,0.59,0.96,1629.67,1625.7
59,60,7546,1,1,md,Training,MLD_Tutoring,83,0,0.21,...,0.32,3872.42,0.03,0.13,2617.45,3743,0.12,0.5,3824,4001.83
60,61,7784,1,1,md,Training,MLD_Tutoring,81,1,0.51,...,0.79,1961.14,0.39,0.75,2166.58,1922.28,0.42,0.83,2072.83,2000
61,62,7045,2,1,md,Training,MLD_Tutoring,88,5,0.46,...,0.86,2582.44,0.33,0.83,2588.46,2527.4,0.33,0.88,2602,2637.48
62,63,7091,2,1,md,Training,MLD_Tutoring,89,21,-0.11,...,0.54,1464.9,0.45,0.75,1890.71,1659.17,0.26,0.33,1870.83,1270.63
63,64,7098,2,1,md,Training,MLD_Tutoring,89,16,0.13,...,0.98,2282.47,0.45,1,2231.46,2231.46,0.41,0.96,2281.21,2333.48
64,65,7170,2,1,md,Training,MLD_Tutoring,83,-3,0.38,...,0.9,2243.44,0.35,0.92,2560.78,2604.77,0.47,0.88,1839.04,1882.1
65,66,7187,2,1,md,Training,MLD_Tutoring,89,-1,0.13,...,0.75,1002.04,0.78,0.79,1036.78,1012.32,0.72,0.71,953.95,991.76
66,67,7188,2,1,md,Training,MLD_Tutoring,88,-8,0.35,...,0.94,1511.36,0.72,0.96,1446.33,1325.39,0.54,0.92,1678.08,1697.32
67,68,7223,2,1,md,Training,MLD_Tutoring,83,17,0.21,...,0.96,1880.57,0.54,0.92,1721.13,1696.64,0.48,1,2064.5,2064.5
68,69,7281,2,1,md,Training,MLD_Tutoring,87,-4,-0.37,...,0.84,1786.08,0.54,0.88,1672.58,1618.62,0.4,0.79,1899.78,1953.53
69,70,7294,2,1,md,Training,MLD_Tutoring,86,-3,0.31,...,0.9,3184.97,0.26,0.88,3535.74,3344.76,0.3,0.92,3066,3025.18
70,71,7322,2,1,md,Training,MLD_Tutoring,90,0,-0.01,...,0.9,1191.94,0.88,0.96,1088.96,1091.52,0.64,0.83,1366.67,1292.35
71,72,7325,2,1,md,Training,MLD_Tutoring,90,2,0.14,...,0.88,1961,0.41,0.88,2234.82,2162.67,0.5,0.88,1963.83,1759.33
72,73,7348,2,1,md,Training,MLD_Tutoring,83,6,0.01,...,0.79,1497.34,0.7,0.83,1163.67,1192.85,0.42,0.75,1793.17,1801.83
73,74,7363,2,1,md,Training,MLD_Tutoring,88,0,-0.02,...,0.69,2621.12,0.32,0.75,2667.86,2374.44,0.22,0.63,3282.81,2867.8
74,75,7366,2,1,md,Training,MLD_Tutoring,89,-4,0.08,...,0.88,1139.32,0.6,0.79,1424.5,1326.11,1.01,0.96,937.79,952.52
75,76,7367,2,1,md,Training,MLD_Tutoring,80,6,0.23,...,0.81,1809.95,0.47,0.79,1809.38,1688.84,0.43,0.83,1972,1931.05
76,77,7397,2,1,md,Training,MLD_Tutoring,86,11,0.29,...,0.94,1025.15,0.84,0.92,1343.21,1090.77,1,0.96,967.13,959.52
77,78,7399,2,1,md,Training,MLD_Tutoring,82,20,0.48,...,0.96,1778.64,0.5,0.96,2050.13,1931.57,0.59,0.96,1629.67,1625.7
78,79,7546,2,1,md,Training,MLD_Tutoring,83,0,0.21,...,0.32,3872.42,0.03,0.13,2617.45,3743,0.12,0.5,3824,4001.83
79,80,7784,2,1,md,Training,MLD_Tutoring,81,1,0.51,...,0.79,1961.14,0.39,0.75,2166.58,1922.28,0.42,0.83,2072.83,2000

write merged df to file

In [ ]:
# merged_df.to_csv(os.path.join(path,'merged_orderedsubj_dataeff_wide_revised.csv'))

### efficiency gain

efficiency gain = post efficiency - pre-efficiency  

eff.comp.num.gain: efficiency gain for num  
eff.comp.dot.gain: efficiency gain for dot

In [ ]:
# merged_df.groupby('visit')[['index_subjlistorder','pid','visit','session','subgroup_type','eff.comp.num.gain','eff.comp.dot.gain']].to_csv(os.path.join(path,'all_subj_eff_compnum_comp_dot_gain.csv'))

In [26]:
comp_num_gain_pre=pd.DataFrame=()
comp_num_gain_post=pd.DataFrame=()
comp_dot_gain_pre=pd.DataFrame=()
comp_dot_gain_post=pd.DataFrame=()

for ix,val in merged_df.groupby('visit'):
    print ix
    if ix == '1':
        comp_num_gain_pre=val[['index_subjlistorder','pid','visit','session','subgroup_type','eff.comp.num.gain']]
        comp_dot_gain_pre=val[['index_subjlistorder','pid','visit','session','subgroup_type','eff.comp.dot.gain']]
    else:
        comp_num_gain_post=val[['index_subjlistorder','pid','visit','session','subgroup_type','eff.comp.num.gain']]
        comp_dot_gain_post=val[['index_subjlistorder','pid','visit','session','subgroup_type','eff.comp.dot.gain']]

1
2

In [ ]:
%%bash
cd /Users/daelsaid/Downloads/subjectlist/
# cat .csv | grep td | awk -F ',' '{print $7}' >> td_eff_compdot_gain_post.csv

### scratch space below

In [ ]:
comp_dot_gain
# comp_dot_gain_pre.to_csv(os.path.join(path,'comp_dot_gain_pre.csv'))
# comp_dot_gain_post.to_csv(os.path.join(path,'comp_dot_gain_post.csv'))
# comp_num_gain_post.to_csv(os.path.join(path,'comp_num_gain_post.csv'))
# comp_num_gain_post.to_csv(os.path.join(path,'comp_num_gain_pre.csv'))

In [ ]:
comp_dot_gain
comp_dot_gain_pre/

# comp_num_gain_pre.to_csv(os.path.join(path,'eff_compnum_gain_all_sub_pre.csv'))
# comp_dot_gain_pre.to_csv(os.path.join(path,'eff_compdot_gain_all_sub_pre.csv'))
# comp_num_gain_post.to_csv(os.path.join(path,'eff_compnum_gain_all_sub_post.csv'))
# comp_dot_gain_post.to_csv(os.path.join(path,'eff_compdot_gain_all_sub_post.csv'))